sforgcompare/urls.py
from django.urls import path
from django.contrib import admin
from compareorgs import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('oauth_response/', views.oauth_response, name='oauth_response'),
    path('job_status/<str:job_id>/', views.job_status),
    path('compare_orgs/<str:job_id>/', views.compare_orgs),
    path('compare_result/<str:job_id>/', views.compare_results),
    path('compare_result/<str:job_id>/build_file/', views.build_file),
    path('re-run-job/<str:job_id>/', views.rerunjob),
    path('check_file_status/<str:job_id>/', views.check_file_status),
    path('get_metadata/<int:component_id>/', views.get_metadata),
    path('get_diffhtml/<int:component_id>/', views.get_diffhtml),
    path('clear/<int:org_number>/', views.clear_org),
]

compareorgs/forms.py
from django import forms

class JobForm(forms.Form):
	org_one = forms.IntegerField(required=False)
	org_two = forms.IntegerField(required=False)
	api_choice = forms.CharField()
	email_choice = forms.CharField()
	email = forms.CharField()
	contextual_diff = forms.BooleanField(required=False, initial=True)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>Salesforce.com Org Compare Tool</title>
        <meta name="keywords" content="salesforce, salesforce.com, force.com, compare, merge, sforgcompare" />
        <meta name="description" content="Compare the all metadata between Salesforce Orgs. Useful for seeing missing changes, customisation and building change sets or deployment packages." />
        <meta name="author" content="Ben Edwards (ben@edwards.nz)" />
        <meta charset="UTF-8" />

        {% block css %}{% endblock %}
        <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}" />
        <!--
        <link rel="shortcut icon" href="{{ STATIC_URL }}images/favicon.ico" type="image/vnd.microsoft.icon" />
        -->
        
        <script type="text/javascript" src="{% static 'js/jquery-1.10.2.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
        <script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
        {% block scripts %}{% endblock %}
        <script>
          (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
          m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
          })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

          ga('create', 'UA-18288189-22', 'auto');
          ga('send', 'pageview');

        </script>
    </head> 

    <body>

        {% if request.GET.noheader != '1' %}

            <!-- Static navbar -->
            <nav class="navbar navbar-default">

                <div class="container-fluid">

                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>

                    <div id="navbar" class="navbar-collapse collapse">

                        <ul class="nav navbar-nav navbar-left">
                            <li>
                                <a href="/" style="padding:5px;">
                                    <img src="{% static 'images/logo-small.png' %}" alt="Org Compare" border="0" />
                                </a>
                            </li>
                            <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</li>
                            <li>
                                <a href="https://cloudtoolkit.co" target="_blank">Salesforce Toolkit</a>
                            </li>
                        </ul>

                        <ul class="nav navbar-nav navbar-right">
                            <li>
                                <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top" style="padding-top:12px;">
                                    <input type="hidden" name="cmd" value="_s-xclick" />
                                    <input type="hidden" name="hosted_button_id" value="9J3KBL2Q4ZUS4" />
                                    <input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donate_LG.gif" border="0" name="submit" title="PayPal - The safer, easier way to pay online!" alt="Donate with PayPal button" />
                                    <img alt="" border="0" src="https://www.paypal.com/en_NZ/i/scr/pixel.gif" width="1" height="1" />
                                </form>
                            </li>
                            <li>
                                <a href="https://github.com/benedwards44/sforgcompare" target="_blank">Source Code</a>
                            </li>
                            <li>
                                <a href="https://twitter.com/benedwards44" target="_blank">@benedwards44</a>
                            </li>
                            <li>
                                <a href="#">
                                    <img src="{% static 'images/i-icon.png' %}" data-toggle="modal" data-target="#infoModal" />
                                </a>
                            </li>
                        </ul>

                    </div><!--/.nav-collapse -->

                </div><!--/.container-fluid -->

            </nav>

            <div class="modal fade" id="infoModal" tabindex="-1" role="dialog" aria-labelledby="infoModalLabel" aria-hidden="true">
                <div class="modal-dialog small_dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">
                                <span aria-hidden="true">&times;</span>
                                <span class="sr-only">Close</span>
                            </button>
                            <h3 class="modal-title" id="apiModalLabel">
                                Salesforce Org Compare
                            </h3>
                        </div>
                        <div class="modal-body">
                            <p>
                                For any errors or issues, please feel free to contact me on twitter <a href="https://twitter.com/benedwards44" target="_blank">@benedwards44</a> or via email <a href="mailto:ben@edwards.nz">ben@edwards.nz</a>.
                            </p>
                            <p>
                                I am constantly trying to update and improve this application, as well as other apps I'm working on. Feel free to contact me if you'd like to contribute or have any ideas. All my applications are open sourced on GitHub at <a href="http://github.com/benedwards44" target="_blank">http://github.com/benedwards44</a>.
                            </p>
                            <p>
                                If you haven't already, check out my other apps at the Salesforce Toolkit Page:<br/>
                                <a href="https://cloudtoolkit.co" target="_blank">https://cloudtoolkit.co</a>
                            </p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </div>

            <div class="clear"></div>

        {% endif %}

        <div class="{% if request.GET.noheader == '1' %}col-md-12{% else %}col-md-8 col-md-offset-2{% endif %}">
            {% block content %}{% endblock %}
        </div>

    </body>

</html>

templates/compare_results.html
{% extends 'base.html' %}

{% load static %}

{% block scripts %}
<script type="text/javascript" src="{% static 'js/jquery-migrate-1.1.0.min.js' %}"></script>
<script type="text/javascript" src="{% static 'jquery-syntaxhighlighter/jquery.syntaxhighlighter.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/compare.js' %}"></script>
{% endblock %}

{% block content %}

	<div class="loading-display">

		<div style="float:left;">
			<img src="{% static 'images/loading.gif' %}" alt="Loading" title="Loading" />
		</div>

		<div style="float:left;margin-left:20px;">
			<h1 style="font-size:1.5em;margin-top:20px;">
				Building results
			</h1>
			<p>
				Shouldn't be long...
			</p>
		</div>

	</div>

	<div id="compare_results">

		<div class="col-md-7">
			<p>
	            Your Org Compare results are presented below. Files are highlighted based on matches or differences. You can click on components to view the file and see highlighted differences within files.
	        </p>
	    </div>

	    <div class="col-md-5 text-right">
	    	<button class="btn btn-warning" onclick="startDownloadJob('{% if job.zip_file %}{{ job.zip_file.url }}{% endif %}', '{{ job.random_id }}');">Download Offline</button> 
	    	&nbsp;&nbsp;
	    	<button class="btn btn-primary" onclick="reRun('{{ job.random_id }}');">Re-Run</button> 
	    </div>

	    <div class="clearfix"></div>

        <hr style="width:100%;margin: 10px 0;" />

        <div class="col-md-5">
	        <select class="form-control" id="display_option">
	            <option value="all">Show All Components</option>
	            <option value="diff" selected="selected">Show Only Differences</option>
	        </select>
	    </div>

	    <div class="col-md-7 text-right">
	        <div id="legend">
	            <div class="alert alert-success legend" role="alert" id="legend_match">
	                Match
	            </div>
	            <div class="alert alert-warning legend" role="alert" id="legend_diff">
	                Diff in file
	            </div>
	            <div class="alert alert-danger legend" role="alert" id="legend_nomatch">
	                New file
	            </div>
	        </div>
	    </div>

        <div style="clear:both;"></div>

		<table class="table table-hover" id="compare_results_table">

			<thead>
				<tr>
					<th><h2>{{ org_left_username }}</h2></th>
					<th><h2>{{ org_right_username }}</h2></th>
				</tr>
			</thead>

			<tbody>
				{% autoescape off %}
					{{ html_rows }}
				{% endautoescape %}
			</tbody>

		</table>

		<div class="alert alert-info" role="alert" id="no_differences_message">
			<p>
				There are no differences between the Orgs selected.
			</p>
		</div>

	</div>

	<div class="modal fade" id="viewCodeModal" tabindex="-1" role="dialog" aria-labelledby="codeModalLabel" aria-hidden="true">
		<div class="modal-dialog">
	    	<div class="modal-content">
	      		<div class="modal-header">
	        		<button type="button" class="close" data-dismiss="modal">
	        			<span aria-hidden="true">&times;</span>
	        			<span class="sr-only">Close</span>
	        		</button>
	        		<h3 class="modal-title" id="codeModalLabel"></h3>
	      		</div>
	      		<div class="modal-body">
	      			<div id="top_scrollbar">
	                    <div id="scrollbar"></div>
	                </div>
	      			<div id="codeModalBody">
	      			</div>
	      		</div>
	      		<div class="modal-footer">
			        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			    </div>
	    	</div>
	  	</div>
	</div>

	<div class="modal fade" id="downloadOfflineModal" tabindex="-1" role="dialog" aria-labelledby="downloadOfflineModalLabel" aria-hidden="true">
		<div class="modal-dialog">
	    	<div class="modal-content">
	      		<div class="modal-header"></div>
	      		<div class="modal-body"></div>
	      		<div class="modal-footer"></div>
	    	</div>
	  	</div>
	</div>

{% endblock %}

templates/compare_results_offline.html
<!DOCTYPE html>
<html>
    <head>
        <title>Salesforce.com Org Compare Tool</title>
        <meta name="keywords" content="salesforce, salesforce.com, force.com, compare, merge, sforgcompare" />
        <meta name="description" content="Compare the all metadata between Salesforce Orgs. Useful for seeing missing changes, customisation and building change sets or deployment packages." />
        <meta name="author" content="Ben Edwards (ben@edwards.nz)" />
        <meta charset="UTF-8" />

        <link rel="stylesheet" href="staticfiles/bootstrap/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="staticfiles/css/styles.css" />
        <link rel="shortcut icon" href="staticfiles/images/favicon.ico" type="image/vnd.microsoft.icon" />
        
        <script type="text/javascript" src="staticfiles/js/jquery-1.10.2.min.js"></script>
        <script type="text/javascript" src="staticfiles/js/main.js"></script>
        <script type="text/javascript" src="staticfiles/bootstrap/js/bootstrap.min.js"></script>
        <script type="text/javascript" src="staticfiles/js/jquery-migrate-1.1.0.min.js"></script>
        <script type="text/javascript" src="staticfiles/jquery-syntaxhighlighter/jquery.syntaxhighlighter.min.js"></script>

        <script type="text/javascript" src="data/components.json"></script>
        <script type="text/javascript" src="staticfiles/js/compare-offline.js"></script>
    </head> 

    <body>

        <!-- Static navbar -->
        <nav class="navbar navbar-default">

            <div class="container-fluid">

                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>

                <div id="navbar" class="navbar-collapse collapse">

                    <ul class="nav navbar-nav navbar-left">
                        <li>
                            <a href="/" style="padding:5px;">
                                <img src="/static/images/logo-small.png" alt="Org Compare" border="0" />
                            </a>
                        </li>
                        <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</li>
                        <li>
                            <a href="https://cloudtoolkit.co" target="_blank">Salesforce Toolkit</a>
                        </li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <a href="https://github.com/benedwards44/sforgcompare" target="_blank">Source Code</a>
                        </li>
                        <li>
                            <a href="https://twitter.com/benedwards44" target="_blank">@benedwards44</a>
                        </li>
                        <li>
                            <a href="#">
                                <img src="/static/images/i-icon.png" data-toggle="modal" data-target="#infoModal" />
                            </a>
                        </li>
                    </ul>

                </div><!--/.nav-collapse -->

            </div><!--/.container-fluid -->

        </nav>

        <div class="modal fade" id="infoModal" tabindex="-1" role="dialog" aria-labelledby="infoModalLabel" aria-hidden="true">
            <div class="modal-dialog small_dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">
                            <span aria-hidden="true">&times;</span>
                            <span class="sr-only">Close</span>
                        </button>
                        <h3 class="modal-title" id="apiModalLabel">
                            Salesforce Org Compare
                        </h3>
                    </div>
                    <div class="modal-body">
                        <p>
                            For any errors or issues, please feel free to contact me on twitter <a href="https://twitter.com/benedwards44" target="_blank">@benedwards44</a> or via email <a href="mailto:ben@edwards.nz">ben@edwards.nz</a>.
                        </p>
                        <p>
                            I am constantly trying to update and improve this application, as well as other apps I'm working on. Feel free to contact me if you'd like to contribute or have any ideas. All my applications are open sourced on GitHub at <a href="http://github.com/benedwards44" target="_blank">http://github.com/benedwards44</a>.
                        </p>
                        <p>
                            If you haven't already, check out my other apps at the Salesforce Toolkit Page:<br/>
                            <a href="https://cloudtoolkit.co" target="_blank">https://cloudtoolkit.co</a>
                        </p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>

        <div class="clear"></div>

        <div class="col-md-8 col-md-offset-2">
        
            <div class="loading-display">

                <div style="float:left;">
                    <img src="staticfiles/images/loading.gif" alt="Loading" title="Loading" />
                </div>

                <div style="float:left;margin-left:20px;">
                    <h1 style="font-size:1.5em;margin-top:20px;">
                        Building results
                    </h1>
                    <p>
                        Shouldn't be long...
                    </p>
                </div>

            </div>

            <div id="compare_results">

                <p>
                    Your Org Compare results are presented below. Files are highlighted based on matches or differences. You can click on components to view the file and see highlighted differences within files.
                </p>

                <hr style="width:100%;margin: 10px 0;" />

                <select class="form-control" id="display_option">
                    <option value="all">Show All Components</option>
                    <option value="diff" selected="selected">Show Only Differences</option>
                </select>

                <div id="legend">
                    <div class="alert alert-success legend" role="alert" id="legend_match">
                        Match
                    </div>
                    <div class="alert alert-warning legend" role="alert" id="legend_diff">
                        Diff in file
                    </div>
                    <div class="alert alert-danger legend" role="alert" id="legend_nomatch">
                        New file
                    </div>
                </div>

                <div style="clear:both;"></div>

                <table class="table table-hover" id="compare_results_table">

                    <thead>
                        <tr>
                            <th><h2>{{ org_left_username }}</h2></th>
                            <th><h2>{{ org_right_username }}</h2></th>
                        </tr>
                    </thead>

                    <tbody>
                        {% autoescape off %}
                            {{ html_rows }}
                        {% endautoescape %}
                    </tbody>

                </table>

                <div class="alert alert-info" role="alert" id="no_differences_message">
                    <p>
                        There are no differences between the Orgs selected.
                    </p>
                </div>

            </div>

            <div class="modal fade" id="viewCodeModal" tabindex="-1" role="dialog" aria-labelledby="codeModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">
                                <span aria-hidden="true">&times;</span>
                                <span class="sr-only">Close</span>
                            </button>
                            <h3 class="modal-title" id="codeModalLabel"></h3>
                        </div>
                        <div class="modal-body">
                            <div id="top_scrollbar">
                                <div id="scrollbar"></div>
                            </div>
                            <div id="codeModalBody">
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </body>

</html>

templates/index.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

	<h1>Salesforce Org Compare</h1>
	<p>
		This tool uses the Salesforce Tooling or Metadata API (user selection) to compare metadata between two Orgs. This is useful when planning deployments or building deployment packages, as well as seeing what configuration exists in Production to Sandbox or between Sandbox environments.
	</p>
	<p>
		None of your organisation information or data is captured or kept from running this tool.
	</p>
	<div class="alert alert-warning alert-dismissible text-center" role="alert">
		<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
		Help keep <strong>Salesforce Org Compare</strong> free! Please donate to support development and Heroku running costs.
		Any value is appreciated!
		<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top" style="padding-top:12px;">
			<input type="hidden" name="cmd" value="_s-xclick" />
			<input type="hidden" name="hosted_button_id" value="9J3KBL2Q4ZUS4" />
			<input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donate_LG.gif" border="0" name="submit" title="PayPal - The safer, easier way to pay online!" alt="Donate with PayPal button" />
			<img alt="" border="0" src="https://www.paypal.com/en_NZ/i/scr/pixel.gif" width="1" height="1" />
		</form>
	</div>
	<div class="alert alert-info alert-dismissible" role="alert">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
		<strong>Note:</strong>
		<ul>
			<li>You will need to be a System Administrator on both Orgs in order to use this application.</li>
			<li>This application uses multiple API calls to your Salesforce Org to retrieve metadata and execute the logic it needs to run. Each Salesforce Org has a 24 hour limit of API calls it can make, and may break other integrations if you exceed this limit.</li>
		</ul>
	</div>

	<div class="left-half">

		<h2>Org One</h2>

		{% if not org_one %}

		<table id="orgOneLogin">

			<tr>
				<td width="125">
					<select id="org_one_env" name="org_one_env" class="form-control">
						<option value="Production">Production</option>
						<option value="Sandbox">Sandbox</option>
					</select>
				</td>
				<td>
					&nbsp;&nbsp;
					<button type="button" id="orgOneButton">
						Login
					</button>
				</td>
			</tr>

		</table>

		{% else %}

		<table id="orgOneDisplay">
			<tr>
				<td width="90"><strong>Username</strong></td>
				<td>{{ org_one.username }}
				</td>
			</tr>
			<tr>
				<td><strong>Org</strong></td>
				<td>{{ org_one.org_name }}</td>
			</tr>
			<tr>
				<td colspan="2" align="center" style="padding-top:5px;">
					<a href="/clear/1">Clear Org</a>
				</td>
			</tr>
		</table>

		{% endif %}

	</div>

	<div class="right-half">

		<h2>Org Two</h2>

		{% if not org_two %}

		<table id="orgTwoLogin">

			<tr>
				<td width="125">
					<select id="org_two_env" name="org_two_env" class="form-control">
						<option value="Production">Production</option>
						<option value="Sandbox">Sandbox</option>
					</select>
				</td>
				<td>
					&nbsp;&nbsp;
					<button type="button" id="orgTwoButton">
						Login
					</button>
				</td>
			</tr>
		</table>

		{% else %}

		<table id="orgTwoDisplay">
			<tr>
				<td width="100"><strong>Username</strong></td>
				<td>{{ org_two.username }}</td>
			</tr>
			<tr>
				<td><strong>Org</strong></td>
				<td>{{ org_two.org_name }}</td>
			</tr>
			<tr>
				<td colspan="2" align="center" style="padding-top:5px;">
					<a href="/clear/2">Clear Org</a>
				</td>
			</tr>
		</table>

		{% endif %}

	</div>

	<div class="clear"></div>

	{% if org_one and org_two %}

	<div id="compareOrgs">

		<form action="." method="POST">

			{% csrf_token %}

			<select id="id_api_choice" name="api_choice" class="form-control">
				<option value="metadata">Metadata API</option>
				<option value="tooling">Tooling API</option>
			</select>

			<img src="{% static 'images/i-icon.png' %}" class="info_icon" data-toggle="modal" data-target="#apiModal" />

			<div style="clear:both;margin: 5px 0;"></div>

			<select id="id_email_choice" name="email_choice" class="form-control">
				<option value="yes" selected="selected">Email me when ready</option>
				<option value="no">Don't email me</option>
			</select>

			<img src="{% static 'images/i-icon.png' %}" class="info_icon" data-toggle="modal" data-target="#emailModal" />

			<div style="clear:both;margin: 5px 0;"></div>

			<input type="email" id="id_email" name="email" placeholder="eg. john@smith.com" class="form-control" value="{{ email }}" />

			<div style="clear:both;margin: 5px 0;"></div>

			<input type="checkbox" id="id_contextual_diff" name="contextual_diff" class="form-control" checked="checked" />
			<label id="id_contextual_diff_label" for="id_contextual_diff">Contextual Diff</label>
			<img src="{% static 'images/i-icon.png' %}" class="info_icon" data-toggle="modal" data-target="#contextModal" style="margin-left:60px;" />

			<div style="clear:both;margin: 5px 0;"></div>

			<input type="submit" id="submitCompare" value="Compare Orgs" />
		</form>

	</div>

	{% endif %}

	<div class="modal fade" id="apiModal" tabindex="-1" role="dialog" aria-labelledby="apiModalLabel" aria-hidden="true">
		<div class="modal-dialog small_dialog">
	    	<div class="modal-content">
	      		<div class="modal-header">
	        		<button type="button" class="close" data-dismiss="modal">
	        			<span aria-hidden="true">&times;</span>
	        			<span class="sr-only">Close</span>
	        		</button>
	        		<h3 class="modal-title" id="apiModalLabel">
	        			API Selection
	        		</h3>
	      		</div>
	      		<div class="modal-body">
	        		<h4>
	        			Tooling API
	        		</h4>
	        		<p>
	        			The Tooling API is much faster in querying the metadata and will return the org compare results a lot faster. However, the Tooling API currently only supports code-based metadata, so is limited to the <a href="#" data-toggle="popover" title="Supported Metadata" data-content="ApexClass <br/>ApexComponent<br/>ApexPage<br/>ApexTrigger" data-html="true" data-trigger="focus">following types of metadata</a>.
	        		</p>

	        		<br/>

	        		<h4>
	        			Metadata API
	        		</h4>
	        		<p>
	        			The Metadata API is slower but returns the full set of queryable metadata for your Org. Use the Metadata API if there are components not contained in the Tooling API that you would like to compare. This should be used if you want a true <strong>full</strong> comparison between two Orgs.
	        			<br/><br/>
	        			Note: The Metadata API is limited to 5,000 files retrieved in a single call.
	        		</p>
	      		</div>
	      		<div class="modal-footer">
			        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			    </div>
	    	</div>
	  	</div>
	</div>

	<div class="modal fade" id="emailModal" tabindex="-1" role="dialog" aria-labelledby="emailModalLabel" aria-hidden="true">
		<div class="modal-dialog small_dialog">
	    	<div class="modal-content">
	      		<div class="modal-header">
	        		<button type="button" class="close" data-dismiss="modal">
	        			<span aria-hidden="true">&times;</span>
	        			<span class="sr-only">Close</span>
	        		</button>
	        		<h3 class="modal-title" id="emailModalLabel">
	        			Email Me
	        		</h3>
	      		</div>
	      		<div class="modal-body">
	        		<p>
	        			For large Orgs, sometimes the process can take some time. If you'd rather do something else instead of staring at an orange loading circle then we can email you a link when the job is done so you can view your results.
	        			<br/><br/>
	        			Note: Because we don't want to store your metadata, the link will only be valid for an hour after the job is done. Once you've viewed your results, we clear all stored information.
	        		</p>
	      		</div>
	      		<div class="modal-footer">
			        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			    </div>
	    	</div>
	  	</div>
	</div>

	<div class="modal fade" id="contextModal" tabindex="-1" role="dialog" aria-labelledby="contextModalLabel" aria-hidden="true">
		<div class="modal-dialog small_dialog">
	    	<div class="modal-content">
	      		<div class="modal-header">
	        		<button type="button" class="close" data-dismiss="modal">
	        			<span aria-hidden="true">&times;</span>
	        			<span class="sr-only">Close</span>
	        		</button>
	        		<h3 class="modal-title" id="emailModalLabel">
	        			Contextual Diff
	        		</h3>
	      		</div>
	      		<div class="modal-body">
	        		<p>
	        			Choose this option to enable a contextual diff. A contextual diff means that compare results will only show the lines of metadata that are deemed to be different, and a number of lines before and after. 
	        			<br/><br/>
	        			This is preferable for large files, as it will only show what is relevant, rather than the entire file.
	        		</p>
	      		</div>
	      		<div class="modal-footer">
			        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			    </div>
	    	</div>
	  	</div>
	</div>

	<input type="hidden" id="client_id" value="{{ client_id }}" />
	<input type="hidden" id="redirect_uri" value="{{ redirect_uri }}" />

	<!-- Force logout when page is loaded -->
	<iframe src="https://login.salesforce.com/secur/logout.jsp" width="0" height="0" style="display:none;"></iframe>
    <iframe src="https://test.salesforce.com/secur/logout.jsp" width="0" height="0" style="display:none;"></iframe>
{% endblock %}